Messages:
  No_Permission: "&4You don't have permission to perform this command!"
  Enable_Glow: "&aNow you are glowing!"
  Disable_Glow: "&cYou aren't glowing anymore!"
  Glow_Status_False: "&cYou are not glowing ❌"
  Glow_Status_True: "&a✔ Glowing! &7Click here to disable"

Inventory:
  Tittle: "&0Select a glow color!"
  Items:
    Aqua_Glow_Name: "&7Click to choose: &bAqua"
    Dark_Aqua_Glow_Name: "&7Click to choose: &3Dark aqua"
    Blue_Glow_Name: "&7Click to choose: &9Blue"
    Dark_Blue_Glow_Name: "&7Click to choose: &1Dark Blue"
    Red_Glow_Name: "&7Click to choose: &cRed"
    Dark_Red_Glow_Name: "&7Click to choose: &4Dark red"
    Yellow_Glow_Name: "&7Click to choose: &eYellow"
    Gold_Glow_Name: "&7Click to choose: &6Gold"
    Lime_Glow_Name: "&7Click to choose: &aLime"
    Green_Glow_Name: "&7Click to choose: &2Green"
    Pink_Glow_Name: "&7Click to choose: &dPink"
    Purple_Glow_Name: "&7Click to choose: &5Purple"
    Black_Glow_Name: "&7Click to choose: &8Black"
    Dark_Gray_Glow_Name: "&7Click to choose: &8Dark gray"
    Gray_Glow_Name: "&7Click to choose: &7BGray"
    White_Glow_Name: "&7Click to choose: &fWhite"
    Color_Lore: "&7Click me to start glowing!"
    Fill_Material_Name: "&7Click on a color!"
    Player_Head:
      Name: "&7Your glowing status:"
      Lore: "&f%glow_status%"


