name: FancyGlow
author: hhitt
version: '1.3.1'
main: hhitt.fancyglow.FancyGlow
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  glow:
    description: enable or disable your glow mode
    usage: /<command>
    aliases:
    - fancyglow
