name: FancyGlow
author: hhitt
version: '1.1'
main: hhitt.fancyglow.FancyGlow
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  glowreload:
    description: reload the plugin config file
    usage: /<command>
    aliases:
      - fancyglowreload
  glow:
    description: enable or disable your glow mode
    usage: /<command>
    aliases:
    - fancyglow
