name: FancyGlow
author: hhitt
version: 2.0.4
main: hhitt.fancyglow.FancyGlow
api-version: '1.20'
softdepend: [ PlaceholderAPI ]
commands:
  glow:
    description: Main FancyGlow command can toggle or select your glow mode.
    usage: /<command>
    aliases:
      - fancyglow
